### ISSUE TITLE
Zen on Pi-Apps using your repo

### ISSUE THREAD

**Issue by Botspot** [ArchitektApx/zen-browser-copr#2]
Until Zen Browser releases their official version, Pi-Apps is using your repo for installing this browser.
https://pi-apps.io/install-app/install-zen-on-raspberry-pi/
There is nothing you need to do, I am just notifying you  to ask that you avoid making breaking changes without notice, such as:

- Deleting the repo
- Deleting files
- Deleting the release tag
- Renaming any necessary files

This has happened before more than once. :)

**Comment by ArchitektApx** [comment]
Hi, alright it's acknowledged :) 

Just be aware of the following changes:
- I've updated the install script based on https://github.com/ArchitektApx/zen-browser-arm64-copr/issues/1 which is now always downloading the latest release in this repo for now (and later on from official sources once they are available for arm64). 
- The release tag is auto-updated with each new build.
